### ISSUE TITLE
无法下载固件包

### ISSUE THREAD

**Issue by PhenTse** [iwrt/iwrt.github.io#1]
【下载地址】
-----------------------------------------------------------
为了让更多的人看到，所以回复可见，不沉贴。
http://pan.lede-project.com/LEDE-X64/Stable-1907-N\

下载页面列表是空的，无法下载固件包了，大神。

**Comment by iwrt** [comment]
网盘挂了，空了再修复，最近比较忙。

**Comment by iwrt** [comment]
http://pan.i-wrt.com/x64/1907/  去这里下载
